feat(banner): add banner
growingio/gio-design pull request #136
Opened 2020-08-20 07:35 UTC by itiiss

2020-08-24 06:24 UTC, jack0pan requested changes

2020-08-24 06:24 UTC, jack0pan commented on packages/components/src/components/banner/Banner.tsx
> +}
新建 `interface.ts` 文件，把 `interface` 定义都放那里。

2020-08-24 09:37 UTC, itiiss commented on packages/components/src/components/banner/Banner.tsx
> +}
调整了

2020-08-26 12:48 UTC, jack0pan approved these changes

2020-08-26 12:49 UTC, merged