add searchbar and refactor input
growingio/gio-design pull request #153
Opened 2020-08-24 11:43 UTC by 1eeing

2020-09-01 07:33 UTC, jack0pan requested changes

2020-09-01 07:33 UTC, jack0pan commented on packages/components/src/components/input/BaseInput.tsx
>  const iconStyle: React.CSSProperties = {
为啥还需要这个？

2020-09-01 07:33 UTC, jack0pan commented on packages/components/src/components/input/Input.tsx
> +    },
```
{
  [`${prefixCls}-content-${size}`]: !!size,
},
```

2020-09-01 07:33 UTC, jack0pan commented on packages/components/src/components/input/Input.tsx
>          placeholder={placeholder}
这几个为啥不放在 `...restInputProps` 里？没看到有其他处理

2020-09-01 11:13 UTC, 1eeing commented on packages/components/src/components/input/BaseInput.tsx
> +}
废弃文件，已删除

2020-09-01 11:14 UTC, 1eeing commented on packages/components/src/components/input/interfaces.ts
> +  [key: string]: any;
react input自带的一些属性用

2020-09-01 11:15 UTC, 1eeing commented on packages/components/src/components/input/interfaces.ts
> +  [key: string]: any;
同上

2020-09-01 11:20 UTC, 1eeing commented on packages/components/src/components/input/Input.tsx
>          placeholder={placeholder}
这里的rest是指我没有定义在接口里的props

2020-09-01 11:30 UTC, 1eeing commented on yarn.lock
> +
多余的库已删

2020-09-01 13:37 UTC, jack0pan commented on packages/components/src/components/input/interfaces.ts
> +  [key: string]: any;
那用 `React.InputHTMLAttributes<HTMLInputElement>`

2020-09-01 13:39 UTC, jack0pan commented on packages/components/src/components/input/Input.tsx
>          placeholder={placeholder}
前面用了 HTMLInputElement，不就可以了吗？

2020-09-08 07:25 UTC, jack0pan approved these changes

2020-09-08 07:53 UTC, merged