refactor(date-picker/list): fix stylelint and eslint error
growingio/gio-design pull request #445
Opened 2020-11-09 11:46 UTC by WORLDI

affects: @gio-design/components

fix stylelint and eslint error

## @gio-design/components@20.10.6

- 日期选择器
  - 修复stylelint和eslint错误
- 列表
  - 修复stylelint和eslint错误

---

## @gio-design/components@20.10.6

- date-picker
  - fix stylelint and eslint error
- list
  - fix stylelint and eslint error

2020-11-11 02:19 UTC, zzt1224 requested changes

2020-11-11 02:19 UTC, zzt1224 commented on .eslintrc.js
> +    'react/destructuring-assignment': 'off',
如果要关eslint放到前端群里讨论一下吧

2020-11-11 02:19 UTC, zzt1224 commented on packages/components/src/components/date-picker/datePicker.tsx
> +  // eslint-disable-next-line react/destructuring-assignment
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/destructuring-assignment.md

2020-11-11 02:19 UTC, zzt1224 commented on packages/components/src/components/date-picker/dateRangePicker.tsx
> +/* eslint-disable @typescript-eslint/no-shadow */
https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-shadow.md

2020-11-11 02:19 UTC, zzt1224 commented on packages/components/src/components/list/Group.tsx
> +    this.props.onSelect && this.props.onSelect(this.props.option);
onSelect 最好在顶部 deconstruct出来 const { onSelect } = this.props;

2020-11-11 02:19 UTC, zzt1224 commented on packages/components/src/components/list/Sortable/SortableItem.tsx
> +  // eslint-disable-next-line react/state-in-constructor
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/state-in-constructor.md

2020-11-11 02:19 UTC, zzt1224 commented on packages/components/src/components/list/Sortable/index.tsx
> +/* eslint-disable react/destructuring-assignment */
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/destructuring-assignment.md

2020-11-11 02:19 UTC, zzt1224 commented on packages/components/src/components/list/Sortable/index.tsx
> +  // eslint-disable-next-line react/static-property-placement
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/static-property-placement.md

2020-11-11 02:19 UTC, zzt1224 commented on packages/components/src/components/list/Sortable/index.tsx
> +  // eslint-disable-next-line react/state-in-constructor
同上

2020-11-11 02:48 UTC, WORLDI commented on packages/components/src/components/date-picker/dateRangePicker.tsx
> +/* eslint-disable @typescript-eslint/no-shadow */
这个规则不是在.eslintrc里面配置了吗，不明白为什么还会报错

2020-11-11 02:50 UTC, WORLDI commented on packages/components/src/components/list/Group.tsx
> +    this.props.onSelect && this.props.onSelect(this.props.option);
这个是个class组件，没法写在顶部，可以写在render()里，但是render函数又要放在handleSelect下面，要不然也报错

2020-11-12 05:33 UTC, zzt1224 approved these changes

2020-11-12 05:33 UTC, zzt1224 commented on packages/components/src/components/list/Group.tsx
> +    onSelect && onSelect(option);
可以这样写 onSelect?.(options)

2020-11-12 07:08 UTC, merged